train_dataset:
  name: div2k
  root_paths: /media02/btlen04/vntan/datasets/TrainingDataset/DIV2K/DIV2K_train_HR/DIV2K_train_HR+/media02/btlen04/vntan/datasets/TrainingDataset/FLICKR
  inp_size:
    - 128
    - 128
  repeat: 5
val_dataset: /media02/btlen04/vntan/datasets/benchmark/Set14/HR

training_batch_size: 32

logger:
  tensorboard: logs/tensorboard
  logging: logs/app.log
  results: logs/results

train_model:
  learning_rate: 0.0001
  checkpoint: pretrained/best_model.pt
  max_epoch: 1000000
  save_path: pretrained
  activate: False
