train_dataset:
  name: div2k
  root_paths: /media02/btlen05/ndbao/dataset/datasets/TrainingDataset/DIV2K/DIV2K_train_HR/DIV2K_train_HR+/media02/btlen05/ndbao/dataset/datasets/TrainingDataset/Flickr2K
  inp_size:
    - 128
    - 128
  repeat: 5
val_dataset: /media02/btlen05/ndbao/dataset/datasets/benchmark/Set14/HR

training_batch_size: 16

logger:
  tensorboard: logs/tensorboard
  logging: logs
  results: logs/results

train_model:
  learning_rate: 0.0002
  checkpoint: pretrained/best_model.pt
  max_epoch: 550
  save_path: pretrained
  activate: False
